export const SHOW_ALERT_NOTIFICATION = "SHOW_ALERT_NOTIFICATION";
export const DELETE_ALERT_NOTIFICATION = "DELETE_ALERT_NOTIFICATION";
export const GET_TOKEN_KEY_SUCCESS = "GET_TOKEN_KEY";
export const DELETE_TOKEN_KEY = "DELETE_TOKEN_KEY";
export const TOGGLE_MIC = "TOGGLE_MIC";
export const TOGGLE_VIDEO = "TOGGLE_VIDEO";
export const SAVE_INFO = "SAVE_INFO";